services:
  mysqldb:
    image: mysql:8.0
    container_name: kandypack-mysql
    restart: always
    environment:
      MYSQL_DATABASE: kandypack_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Automatically populates schemas, procedures, functions, triggers, views & seed data on initialization
      - ./database/docker-init.sql:/docker-entrypoint-initdb.d/01_init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: kandypack-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kandypack_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      DB_PASSWORD: root

volumes:
  mysql_data: