// Serves as an Object-Relational Mapping (ORM) component 
// Bridges Java application with the Driver table in MySQL

package com.kandypack.logistics.delivery.entity;

import jakarta.persistence.*; // for JPA annotations that start with @Entity, @Table, @Id, @GeneratedValue, and @Column

@Entity
@Table(name = "Driver") //Directly maps this class to the database table named Driver

public class Driver {
    @Id // For PK = DriverId
    @GeneratedValue(strategy = GenerationType.IDENTITY) //IDs are generated by database through AUTO_INCREMENT
    @Column(name = "DriverID")
    private Integer driverId;

    @Column(name = "Name", nullable = false, length = 100)
    private String name;

    @Column(name = "LicenceNumber", nullable = false, unique = true, length = 30)
    private String licenseNumber;

    @Column(name = "ContactNumber", nullable = false, length = 15)
    private String contactNumber;

    // Default constructor
    // Instantiate the object using default constructor before populating the fields
    public Driver() {}

    // Getters and Setters
    public Integer getDriverId() { return driverId; }
    public void setDriverId(Integer driverId) { this.driverId = driverId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getLicenseNumber() { return licenseNumber; }
    public void setLicenseNumber(String licenseNumber) { this.licenseNumber = licenseNumber; }

    public String getContactNumber() { return contactNumber; }
    public void setContactNumber(String contactNumber) { this.contactNumber = contactNumber; }
}